# Generated by Django 3.0.2 on 2020-01-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_qoh'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(default='Admission to one or more of the following Resort attractions for each day of the ticket'),
        ),
    ]
